name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Add environment variables
        env:
          REACT_APP_SPREADSHEET_API_KEY: ${{ secrets.REACT_APP_SPREADSHEET_API_KEY }}
          REACT_APP_SPREADSHEET_ID: ${{ secrets.REACT_APP_SPREADSHEET_ID }}
        run: |
          echo "REACT_APP_SPREADSHEET_API_KEY is $REACT_APP_SPREADSHEET_API_KEY"
          echo "REACT_APP_SPREADSHEET_ID is $REACT_APP_SPREADSHEET_ID"

      - name: Pass secrets to a script
        run: |
          echo "export REACT_APP_SPREADSHEET_API_KEY=${{ secrets.REACT_APP_SPREADSHEET_API_KEY }}" >> $GITHUB_ENV
          echo "export REACT_APP_SPREADSHEET_ID=${{ secrets.REACT_APP_SPREADSHEET_ID }}" >> $GITHUB_ENV
  
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
